### ISSUE TITLE
Loading layer with CSW API fails when title and name are different

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/qgis_geonode#140]
It is possible that a layer's `name` and `title` be different. As an example (showing only the relevant JSON properties):

```
GET https://somalia.gep.kartoza.com/api/layers/42/

{
	"abstract": "Mini-grid locations as reported in the Power Master Plan, by the state focal points involved in the data collection or online sources.",
	"abstract_en": "Mini-grid locations as reported in the Power Master Plan, by the state focal points involved in the data collection or online sources.",
	"alternate": "geonode:Existing_mini_grids",
	"detail_url": "/layers/geonode_data:geonode:Existing_mini_grids",
	"name": "Existing_mini_grids",
	"resource_uri": "/api/layers/42/",
	"title": "Existing mini-grids",
	"title_en": "Existing mini-grids",
	"typename": "geonode:Existing_mini_grids",
	"uuid": "648f159c-5595-11eb-a268-0242ac120005",
}
```

We seem to be using `name` or `title` as search parameter somewhere when a layer is being loaded onto QGIS. This fails with:

```python
OSError: Received unexpected API response for layer 'Existing_mini_grids' details: url: https://somalia.gep.kartoza.com/api/layers/?title=Existing_mini_grids payload: {'geonode_version': '3.0.0', 'meta': {'limit': 200, 'next': None, 'offset': 0, 'previous': None, 'total_count': 0}, 'objects': []} cookies: {'csrftoken': Cookie(version=0, name='csrftoken', value='WssVG944TC3nVSGgjmOZCriP7851mq32AwjkiHjdhW88tV4W4k9PYTDhgh7PvLtA', port=None, port_specified=False, domain='somalia.gep.kartoza.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1646816873, discard=False, comment=None, comment_url=None, rest={'SameSite': 'Lax'}, rfc2109=False), 'sessionid': Cookie(version=0, name='sessionid', value='27pfwo6ch8d21o4q2porrsy1gdmts2ol', port=None, port_specified=False, domain='somalia.gep.kartoza.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1616576872, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None, 'SameSite': 'Lax'}, rfc2109=False)} 
Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/csw.py", line 348, in blocking_get_layer_detail
    layer_detail = payload["objects"][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/base.py", line 232, in response_fetched
    handler(payload)
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/csw.py", line 318, in handle_layer_detail
    layer_detail = self.blocking_get_layer_detail(layer_title)
  File "/home/ricardo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_geonode/apiclient/csw.py", line 350, in blocking_get_layer_detail
    raise IOError(
OSError: Received unexpected API response for layer 'Existing_mini_grids' details: url: https://somalia.gep.kartoza.com/api/layers/?title=Existing_mini_grids payload: {'geonode_version': '3.0.0', 'meta': {'limit': 200, 'next': None, 'offset': 0, 'previous': None, 'total_count': 0}, 'objects': []} cookies: {'csrftoken': Cookie(version=0, name='csrftoken', value='WssVG944TC3nVSGgjmOZCriP7851mq32AwjkiHjdhW88tV4W4k9PYTDhgh7PvLtA', port=None, port_specified=False, domain='somalia.gep.kartoza.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1646816873, discard=False, comment=None, comment_url=None, rest={'SameSite': 'Lax'}, rfc2109=False), 'sessionid': Cookie(version=0, name='sessionid', value='27pfwo6ch8d21o4q2porrsy1gdmts2ol', port=None, port_specified=False, domain='somalia.gep.kartoza.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1616576872, discard=False, comment=None, comment_url=None, rest={'HttpOnly': None, 'SameSite': 'Lax'}, rfc2109=False)}

```

Note the invalid URL being used - it contains the layer `name` as a search value, but it is using `title` as the search parameter. Maybe we can switch to using the layer's `uuid` instead?

**Comment by Samweli** [comment]
using `uuid` result into `{"error": "The 'uuid' field does not allow filtering."}`, may be we use 'id' instead of `uuid`.?

**Comment by ricardogsilva** [comment]
@Samweli 

As long as it works with both the `APIv2` and `CSW` API clients I don't care about the actual implementation details so much :wink: 

However, keep in mind that the `CSW` API does not know about a layer's id
