### ISSUE TITLE
Error 'Could not find a connection named '' in QgsSettings'  after launching the Data source Manager 

### ISSUE THREAD

**Issue by geogeek11** [kartoza/qgis_geonode#170]
After installing the plugin successfully, I launch the Data source Manager dialog, the dialog is not launched and I get the stack trace below :

``` ValueError: Could not find a connection named '' in QgsSettings 
Traceback (most recent call last):
  File "C:/Users/Administrateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_source_select_provider.py", line 37, in createDataSourceWidget
    return GeonodeDataSourceWidget(parent, fl, widgetMode)
  File "C:/Users/Administrateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_source_select_provider.py", line 164, in __init__
    self.update_current_connection(self.connections_cmb.currentIndex())
  File "C:/Users/Administrateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\gui\geonode_source_select_provider.py", line 309, in update_current_connection
    current_connection = settings_manager.find_connection_by_name(current_text)
  File "C:/Users/Administrateur/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_geonode\conf.py", line 195, in find_connection_by_name
    f"Could not find a connection named {name!r} in QgsSettings"
ValueError: Could not find a connection named '' in QgsSettings


Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.18.1-Zürich Zürich, 202f1bf7e5  ```

**Comment by ricardogsilva** [comment]
This has been fixed by some of the latest commits, not entirely sure which. Trying out the plugin on a fresh QGIS profile does not yield this error.
