### ISSUE TITLE
NotImplementedError when searching only maps

### ISSUE THREAD

**Issue by giohappy** [kartoza/qgis_geonode#179]
I received a NotImplementedError when searching for maps on GeoNode master demo.
After the error any further search is disabled.

![image](https://user-images.githubusercontent.com/571129/142906276-9bc7137d-f129-4049-8c0b-e048e42d6a64.png)

```
NotImplementedError 
Traceback (most recent call last):
  File ".../python/plugins\qgis_geonode\gui\geonode_source_select_provider.py", line 440, in search_geonode
    spatial_extent=spatial_extent_epsg4326,
  File ".../python/plugins\qgis_geonode\apiclient\base.py", line 156, in get_layers
    QtNetwork.QNetworkRequest(self.get_layers_url_endpoint(params)),
  File ".../python/plugins\qgis_geonode\apiclient\apiv2.py", line 57, in get_layers_url_endpoint
    query = self._build_search_query(search_params)
  File ".../python/plugins\qgis_geonode\apiclient\apiv2.py", line 124, in _build_search_query
    raise NotImplementedError
NotImplementedError
```

**Comment by ricardogsilva** [comment]
Maps support has not been implemented yet, so I removed them from the UI for now
