### ISSUE TITLE
Error authenticating

### ISSUE THREAD

**Issue by timlinux** [kartoza/qgis_geonode#231]
```python
An error has occurred while executing Python code: 

AttributeError: 'LegacyVersion' object has no attribute 'major' 
Traceback (most recent call last):
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/qgis_geonode/gui/connection_dialog.py", line 143, in handle_discovery_test
    self.update_connection_details()
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/qgis_geonode/gui/connection_dialog.py", line 156, in update_connection_details
    client: BaseGeonodeClient = apiclient.get_geonode_client(current_settings)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/qgis_geonode/apiclient/__init__.py", line 13, in get_geonode_client
    class_path = select_client_class_path(connection_settings.geonode_version)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/qgis_geonode/apiclient/__init__.py", line 24, in select_client_class_path
    if geonode_version.major == 4:
AttributeError: 'LegacyVersion' object has no attribute 'major'

```

**Comment by timlinux** [comment]
Note that I deleted the authdb config and then created it again then pressed Test Connection.

**Comment by timlinux** [comment]
Restarting QGIS resolves the issue

**Comment by ricardogsilva** [comment]
This seems related to geosolutions-it/nexus-geonode#579
